In [1]:
import diagonalizer
from diagonalizer import diagonalize_1D, density_plot_1D, pSweep_1D, spectrum_plot_1D, FermiVelocityZQL

import numpy as np
from numpy import pi
from copy import copy
# for plotting
import matplotlib as mpl
from matplotlib import pyplot as plt

#Some global and default parameters
SitesCount_XDefault = 1000
fsys_1D = diagonalizer.FinalizedSystem_1D(SitesCount_XDefault)

# Set-4

In [2]:
ParametersSet4 = diagonalizer.SimpleNamespace( tp=2., t=1., tzp=1., tz=1., M0= 0., FermiEnergy = 0., \
                     betaz=3., b0=0.2, pzNode2 = -1.69329, EnergyNode2 = 0.0661671, \
                     Rescale_hop0 = 1.0, Rescale_onsite0 = 1.0, Rescale_onsite1 = 1.0, \
                     lBinv2=0., x_shift= (SitesCount_XDefault - 1.)/2., \
                     EigenvectorsCount = 50, EnergyPrecision = 10**(-5), WavefunctionComponents = 4, \
                     py = 0., pz = 0. )

In [3]:
params = copy(ParametersSet4)

params.lBinv2 = 1. / 40.**2

pzStart = -1.59
pzEnd = 1.78


GridNumber = 20
for i in range(GridNumber):
    params.pz = pzStart + i * (pzEnd - pzStart) / (GridNumber-1)
    velocityCash = FermiVelocityZQL(fsys_1D, params)
    print('{', params.pz, ',', velocityCash,sep='',end='},')
    
print('')    
    
GridNumber = 40
for i in range(GridNumber):
    params.pz = pzStart + i * (pzEnd - pzStart) / (GridNumber-1)
    velocityCash = FermiVelocityZQL(fsys_1D, params)
    print('{', params.pz, ',', velocityCash,sep='',end='},')

{-1.59,-0.659661690999},{-1.4126315789473685,-0.0355852814687},{-1.2352631578947368,-0.0303907349455},{-1.0578947368421052,-0.0363373437554},{-0.8805263157894737,-0.0437937387831},{-0.7031578947368421,-0.0507892312835},WARNING: Two values of energies become close to each other. Try increasing the number of lattice sites
{-0.5257894736842106,-0.056672922877},{-0.34842105263157896,-0.061287225949},{-0.17105263157894735,-0.0646934141721},{0.006315789473684275,-0.0667072072984},{0.1836842105263159,-0.0665979338601},{0.3610526315789473,-0.0637354622003},WARNING: Two values of energies become close to each other. Try increasing the number of lattice sites
{0.5384210526315789,-0.0581718512345},WARNING: Two values of energies become close to each other. Try increasing the number of lattice sites
{0.7157894736842108,-0.0502864470665},WARNING: Two values of energies become close to each other. Try increasing the number of lattice sites
{0.8931578947368422,-0.0403316603563},{1.070526315789474,-0.

## FA spectrum is additively separable (for the non-deformed boundary)

In [10]:
params = copy(ParametersSet4)

fsys_finerResolution = diagonalizer.FinalizedSystem_1D(1000)
params.EigenvectorsCount = 4

params.FermiEnergy = 0.
params.pz = -0.3
params.py = 0.
evals, evecs = diagonalize_1D(fsys_finerResolution,params)
print(evals)

params.FermiEnergy = 0.
params.pz = 0.
params.py = 0.05
evals, evecs = diagonalize_1D(fsys_finerResolution,params)
print(evals)

params.pz = -0.3
params.py = 0.05
params.FermiEnergy = -0.1
evals, evecs = diagonalize_1D(fsys_finerResolution,params)
print(evals)
print(0.01970135+0.09973596)

[-0.55414988 -0.55403861  0.01970135  0.01970135]
[-0.51362905 -0.09973596  0.09973596  0.51359171]
[-0.56418814 -0.56394363 -0.08003461  0.11943731]
0.11943730999999999


## Extraction of the FA z-velocity around a Weyl node 

In [24]:
fsys_finerResolution = diagonalizer.FinalizedSystem_1D(10000)
params = copy(ParametersSet4)

params.pz = params.pzNode2
params.FermiEnergy = params.EnergyNode2
params.EigenvectorsCount = 4
evals, evecs = diagonalize_1D(fsys_finerResolution,params)
print(evals, 'while the expected Weyl-node energy is', params.EnergyNode2)


params.pz = params.pzNode2 + 0.1
params.FermiEnergy = params.EnergyNode2
params.EigenvectorsCount = 4
evals, evecs = diagonalize_1D(fsys_finerResolution,params)
print(evals)

params.pz = params.pzNode2 + 0.2
params.FermiEnergy = params.EnergyNode2
params.EigenvectorsCount = 4
evals, evecs = diagonalize_1D(fsys_finerResolution,params)
print(evals)


#The extraction of the FA spectrum is made manually so far
print((0.06646653 - 0.0666498)/(0.2-0.1))


del fsys_finerResolution, params, evals, evecs

[ 0.06521745  0.06584527  0.06647143  0.06709927] while the expected Weyl-node energy is 0.0661671
[ 0.00163194  0.00164055  0.0666498   0.0666498 ]
[-0.06663813 -0.06663399  0.06646653  0.06646653]
-0.0018326999999999927


## What is the Fermi velocity profile for a deformed boundary?

In [3]:
params = copy(ParametersSet4)
params.Rescale_b0_0 = 10.0

# evals, evecs = pSweep_1D( fsys_1D, params, -2., 0., pCount=20, yORzSweep = 'pzSweep')
# spectrum_plot_1D(evals, -2., 0., pCount=20)
pzStart = -1.59
pzEnd = 1.78
params.lBinv2 = 1. / 40.**2

GridNumber = 20

In [4]:
for i in range(GridNumber):
    params.pz = pzStart + i * (pzEnd - pzStart) / (GridNumber-1)
    velocityCash = FermiVelocityZQL(fsys_1D, params, pyGuess = 0.7)
    print('{', params.pz, ',', velocityCash,sep='',end='},')

{-1.59,-0.553373762004},{-1.4126315789473685,0.427655194922},{-1.2352631578947368,0.352347181816},{-1.0578947368421052,0.214907897289},{-0.8805263157894737,0.0344924962145},{-0.7031578947368421,-0.164817156884},{-0.5257894736842106,-0.35113817503},{-0.34842105263157896,-0.48681827025},{-0.17105263157894735,-0.548763939988},{0.006315789473684275,-0.560206860005},{0.1836842105263159,-0.547572538573},{0.3610526315789473,-0.480247710263},{0.5384210526315789,-0.339023199572},{0.7157894736842108,-0.149673382621},{0.8931578947368422,0.0503382527303},{1.070526315789474,0.230114199321},{1.2478947368421054,0.367122844837},{1.4252631578947368,0.447042101902},{1.6026315789473686,0.476083932167},{1.78,0.64481234413},