In [1]:
import diagonalizer
from diagonalizer import diagonalize_1D, density_plot_1D, pSweep_1D, spectrum_plot_1D, FermiVelocityZQL

import numpy as np
from numpy import pi
from copy import copy
# for plotting
import matplotlib as mpl
from matplotlib import pyplot as plt

#Some global and default parameters
SitesCount_XDefault = 1000
fsys_1D = diagonalizer.FinalizedSystem_1D(SitesCount_XDefault)

# Set-4

In [2]:
ParametersSet4 = diagonalizer.SimpleNamespace( tp=2., t=1., tzp=1., tz=1., M0= 0., FermiEnergy = 0., \
                     betaz=3., b0=0.2, pzNode2 = -1.69329, EnergyNode2 = 0.0661671, \
                     Rescale_hop0 = 1.0, Rescale_onsite0 = 1.0, Rescale_onsite1 = 1.0, \
                     lBinv2=0., x_shift= (SitesCount_XDefault - 1.)/2., \
                     EigenvectorsCount = 50, EnergyPrecision = 10**(-5), WavefunctionComponents = 4, \
                     py = 0., pz = 0. )

In [4]:
params = copy(ParametersSet4)

params.lBinv2 = 1. / 40.**2

pzStart = -1.59
pzEnd = 1.78


GridNumber = 5
for i in range(GridNumber):
    params.pz = pzStart + i * (pzEnd - pzStart) / (GridNumber-1)
    velocityCash = FermiVelocityZQL(fsys_1D, params, pyGuess = 0.35, pyGuess2 = 0.23, debug = True)
    print('{', params.pz, ',', velocityCash,sep='',end='},')

pyF = 0.2549006080599639
      converged: True
           flag: 'converged'
 function_calls: 12
     iterations: 11
           root: 0.2549006080599639
Energy = -4.57765400325e-07
Velocity calculated by approximate differentiation is 170.3913661
{-1.59,-0.659823201878},pyF = 0.28924962430437423
      converged: True
           flag: 'converged'
 function_calls: 4
     iterations: 3
           root: 0.28924962430437423
Energy = 4.91530562462e-05
Velocity calculated by approximate differentiation is 4.01446743966e-06
{-0.7475,-0.0491681329775},pyF = 0.3147889420622757
      converged: True
           flag: 'converged'
 function_calls: 4
     iterations: 3
           root: 0.3147889420622757
Energy = -3.35012250525e-05
Velocity calculated by approximate differentiation is -0.100472662415
{0.09499999999999997,-0.0669711830791},pyF = 0.3387689946111496
      converged: True
           flag: 'converged'
 function_calls: 4
     iterations: 3
           root: 0.3387689946111496
Energy = -7.510

In [9]:
GridNumber = 40
for i in range(GridNumber):
    params.pz = pzStart + i * (pzEnd - pzStart) / (GridNumber-1)
    velocityCash = FermiVelocityZQL(fsys_1D, params, pyGuess = 0.35, pyGuess2 = 0.23)
    print('{', params.pz, ',', velocityCash,sep='',end='},')

{-1.59,-0.659670650855},{-1.5035897435897436,-0.0671347767029},{-1.4171794871794872,-0.03621025061},{-1.330769230769231,-0.0301334241031},{-1.2443589743589745,-0.03021805235},{-1.157948717948718,-0.0325416645768},{-1.0715384615384616,-0.0357837578805},{-0.9851282051282052,-0.0393765213692},{-0.8987179487179487,-0.0430326492485},{-0.8123076923076923,-0.0465891446685},{-0.7258974358974359,-0.0499469158461},{-0.6394871794871796,-0.0530452195217},{-0.5530769230769232,-0.0558504076334},{-0.4666666666666668,-0.0583504246455},{-0.3802564102564103,-0.0605499905938},{-0.29384615384615387,-0.06246217345},{-0.2074358974358974,-0.0640936884434},{-0.12102564102564117,-0.0654254899654},{-0.03461538461538449,-0.0663983630146},{0.051794871794871744,-0.0669166734522},{0.1382051282051282,-0.0668745168531},{0.22461538461538444,-0.0661905490523},{0.3110256410256409,-0.0648298550868},{0.3974358974358976,-0.062802910909},{0.4838461538461536,-0.0601489405653},{0.57025641025641,-0.0569168833652},{0.6566666666

## Several additional points, in order to make the approximation better

In [8]:
params.pz = pzStart + 0.2 * (pzEnd - pzStart) / (GridNumber-1)
velocityCash = FermiVelocityZQL(fsys_1D, params, pyGuess = 0.28, pyGuess2 = 0.24)
print('{', params.pz, ',', velocityCash,sep='',end='},')

params.pz = pzStart + 0.4 * (pzEnd - pzStart) / (GridNumber-1)
velocityCash = FermiVelocityZQL(fsys_1D, params, pyGuess = 0.28, pyGuess2 = 0.24)
print('{', params.pz, ',', velocityCash,sep='',end='},')

params.pz = pzStart + 0.6 * (pzEnd - pzStart) / (GridNumber-1)
velocityCash = FermiVelocityZQL(fsys_1D, params, pyGuess = 0.28, pyGuess2 = 0.24)
print('{', params.pz, ',', velocityCash,sep='',end='},')

params.pz = pzStart + 0.8 * (pzEnd - pzStart) / (GridNumber-1)
velocityCash = FermiVelocityZQL(fsys_1D, params, pyGuess = 0.28, pyGuess2 = 0.24)
print('{', params.pz, ',', velocityCash,sep='',end='},')

params.pz = pzStart + 1.5 * (pzEnd - pzStart) / (GridNumber-1)
velocityCash = FermiVelocityZQL(fsys_1D, params, pyGuess = 0.28, pyGuess2 = 0.24)
print('{', params.pz, ',', velocityCash,sep='',end='},')

{-1.5727179487179488,-0.303000314881},{-1.5554358974358975,-0.167211394606},{-1.5381538461538462,-0.112458609859},{-1.520871794871795,-0.0840789668997},{-1.4603846153846154,-0.0455343568806},

## FA spectrum is additively separable (for the non-deformed boundary)

In [10]:
params = copy(ParametersSet4)

fsys_finerResolution = diagonalizer.FinalizedSystem_1D(1000)
params.EigenvectorsCount = 4

params.FermiEnergy = 0.
params.pz = -0.3
params.py = 0.
evals, evecs = diagonalize_1D(fsys_finerResolution,params)
print(evals)

params.FermiEnergy = 0.
params.pz = 0.
params.py = 0.05
evals, evecs = diagonalize_1D(fsys_finerResolution,params)
print(evals)

params.pz = -0.3
params.py = 0.05
params.FermiEnergy = -0.1
evals, evecs = diagonalize_1D(fsys_finerResolution,params)
print(evals)
print(0.01970135+0.09973596)

[-0.55414988 -0.55403861  0.01970135  0.01970135]
[-0.51362905 -0.09973596  0.09973596  0.51359171]
[-0.56418814 -0.56394363 -0.08003461  0.11943731]
0.11943730999999999


## Extraction of the FA z-velocity around a Weyl node 

In [24]:
fsys_finerResolution = diagonalizer.FinalizedSystem_1D(10000)
params = copy(ParametersSet4)

params.pz = params.pzNode2
params.FermiEnergy = params.EnergyNode2
params.EigenvectorsCount = 4
evals, evecs = diagonalize_1D(fsys_finerResolution,params)
print(evals, 'while the expected Weyl-node energy is', params.EnergyNode2)


params.pz = params.pzNode2 + 0.1
params.FermiEnergy = params.EnergyNode2
params.EigenvectorsCount = 4
evals, evecs = diagonalize_1D(fsys_finerResolution,params)
print(evals)

params.pz = params.pzNode2 + 0.2
params.FermiEnergy = params.EnergyNode2
params.EigenvectorsCount = 4
evals, evecs = diagonalize_1D(fsys_finerResolution,params)
print(evals)


#The extraction of the FA spectrum is made manually so far
print((0.06646653 - 0.0666498)/(0.2-0.1))


del fsys_finerResolution, params, evals, evecs

[ 0.06521745  0.06584527  0.06647143  0.06709927] while the expected Weyl-node energy is 0.0661671
[ 0.00163194  0.00164055  0.0666498   0.0666498 ]
[-0.06663813 -0.06663399  0.06646653  0.06646653]
-0.0018326999999999927
